package kz.proctoring.domain.enums;
public enum EventType {
    TAB_SWITCH, FACE_NOT_DETECTED, MULTIPLE_FACES, PHONE_DETECTED,
    NOISE_DETECTED, HEAD_TURN, BROWSER_MINIMIZE, COPY_PASTE, SUSPICIOUS_ACTIVITY
}
